/*==============================================================================
	C++ class definitions exported from script.
	This is automatically generated by the tools.
	DO NOT modify this manually! Edit the corresponding .uc files instead!
==============================================================================*/


#ifndef __CORECLASSES_H__
#define __CORECLASSES_H__

#endif // __CORECLASSES_H__
