/*=============================================================================
	C++ class definitions exported from script.
	This is automatically generated by the tools.
	DO NOT modify this manually! Edit the corresponding .uc files instead!
=============================================================================*/


#ifndef __CORECLASSES_H__
#define __CORECLASSES_H__

/*-----------------------------------------------------------------------------
	Forward declarations
-----------------------------------------------------------------------------*/

class CObject;


/*-----------------------------------------------------------------------------
	Class registration
-----------------------------------------------------------------------------*/

#define REGISTER_CORE_CLASSES


#endif // __CORECLASSES_H__
